name: ci

on: [ push, pull_request ]

jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up PHP 7.4
    uses: shivammathur/setup-php@2.7.0
    with:
     php-version: 7.4
  - run: composer install
  - run: composer run lint
 test:
  runs-on: ubuntu-latest
  strategy:
   matrix:
    php-version: [ 7.2, 7.3, 7.4, 8.0, 8.1 ]
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up PHP ${{ matrix.php-version }}
    uses: shivammathur/setup-php@2.7.0
    with:
     php-version: ${{ matrix.php-version }}
  - run: composer require phpunit/phpunit 9 --dev --no-update
    if: matrix.php-version > 7.4
  - run: composer install --ignore-platform-reqs
    if: matrix.php-version > 7.4
  - run: composer install
    if: matrix.php-version < 8
  - run: composer run test
 report:
  needs: test
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up PHP 7.4
    uses: shivammathur/setup-php@2.7.0
    with:
     php-version: 7.4
  - run: composer global require twinh/php-coveralls
  - run: composer install
  - name: Report to coveralls
    run: php-coveralls --coverage_clover=build/logs/clover.xml
    env:
     COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
