name: ci

on: [ push, pull_request ]

jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up PHP 8.0
    uses: shivammathur/setup-php@2.17.0
    with:
     php-version: 8.0
  - run: composer install
  - run: composer run lint
 test:
  runs-on: ubuntu-latest
  strategy:
   matrix:
    php-version: [ 8.0, 8.1 ]
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up PHP ${{ matrix.php-version }}
    uses: shivammathur/setup-php@2.17.0
    with:
     php-version: ${{ matrix.php-version }}
  - run: composer install --ignore-platform-reqs
  - run: composer run test
